export const GET_SHOPPING_LISTS = 'GET_SHOPPING_LISTS';
export const PUT_SHOPPING_LIST = 'PUT_SHOPPING_LIST';
export const POST_SHOPPING_LIST = 'PUT_SHOPPING_LIST';
export const SET_SHOPPING_LIST = 'SET_SHOPPING_LIST';

export const GET_SHOPPING_CART = 'GET_SHOPPING_CART';
export const PUT_SHOPPING_CART = 'PUT_SHOPPING_CART';
export const PUT_SHOPPING_CART_ITEM = 'PUT_SHOPPING_CART_ITEM';
export const DELETE_SHOPPING_CART_ITEM = 'DELETE_SHOPPING_CART_ITEM';
export const SHOW_LOADING_SHOPPING_CART_ITEM = 'SHOW_LOADING_SHOPPING_CART_ITEM';

export const GET_PRODUCTS_BY_DESCRIPTION = 'GET_PRODUCTS_BY_DESCRIPTION';
export const GET_PRODUCTS_BY_EAN = 'GET_PRODUCTS_BY_EAN';
export const CLEAR_PRODUCT_LIST = 'CLEAR_PRODUCT_LIST';



export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const DEFAULT_LOADING = 'DEFAULT_LOADING';
export const OFF_LOADING = 'OFF_LOADING';
export const ON_LOADING = 'ON_LOADING';
export const ERROR = 'ERROR';
export const SHOW_ALERT = 'SHOW_ALERT';