import { useMemo } from "react";

const useConstants = () => {
  const USER_LOGGER = "@USER_LOGGER";

  const SET_USER_INFO_LOGGED = "@SET_USER_INFO_LOGGED";
  const SET_IS_LOGGED = "@SET_IS_LOGGED";
  const SET_SHOPPING_LISTS = "@SET_SHOPPING_LISTS";
  const SET_SELECTED_SHOPPING_LIST = "@SET_SELECTED_SHOPPING_LIST";
  const SET_SHOPPING_LIST_TO_SAVE = "@SET_SHOPPING_LIST_TO_SAVE";
  const SET_ITEM_TO_SAVE = "@SET_ITEM_TO_SAVE";
  const SET_SELECTED_ITEM = "@SET_SELECTED_ITEM";
  const SET_ITEMS = "@SET_ITEMS";
  const SET_PRODUCT_DETAILS = "@SET_PRODUCT_DETAILS";
  const SET_SEARCH_CODE = "@SET_SEARCH_CODE";
  const SET_SEARCH_TERM = "@SET_SEARCH_TERM";
  const SET_SEARCH_RESULTS = "@SET_SEARCH_RESULTS";
  const SET_UNITS = "@SET_UNITS";

  return {
    USER_LOGGER,
    SET_USER_INFO_LOGGED,
    SET_IS_LOGGED,
    SET_SHOPPING_LISTS,
    SET_SELECTED_SHOPPING_LIST,
    SET_SHOPPING_LIST_TO_SAVE,
    SET_ITEM_TO_SAVE,
    SET_SELECTED_ITEM,
    SET_ITEMS,
    SET_PRODUCT_DETAILS,
    SET_SEARCH_CODE,
    SET_SEARCH_TERM,
    SET_SEARCH_RESULTS,
    SET_UNITS,
  };
};

export default useConstants;
